services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Event Listener Services
    # DomainException Listener
    App\EventListener\IExceptionListener:
      class: App\EventListener\DetailExceptionListener
      tags:
        - { name: kernel.event_listener, event: kernel.exception }