services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    Behatch\HttpCall\Request: ~

    # Event Listener Services
    # DomainException Listener
    App\EventListener\IExceptionListener:
      class: App\EventListener\DetailExceptionListener
      tags:
        - { name: kernel.event_listener, event: kernel.exception }